### ISSUE TITLE
npmignore `PST file format.pdf` and other unnecessary files

### ISSUE THREAD

**Issue by SheetJSDev** [epfromer/pst-extractor#2]
`pst-extractor` is awesome!  We were able to churn through the entire Enron corpus and [extract over 17K spreadsheets](https://github.com/SheetJS/enron_xls) fairly quickly.

Issue #1 already covered the extraneous npm dependencies.  This issue is about extraneous files in the published module:

https://unpkg.com/pst-extractor@1.2.2/ shows the current listing, and the following files are probably unnecessary (they can be ignored through the `.npmignore` mechanism):

- `PST file format.pdf` 7.46MB!
- `contributing.md`
- `.jshintrc`
- `mocha.opts`

**Comment by epfromer** [comment]
Good to hear you are finding it useful.  I'm working on an update that is forthcoming in the next week, and will remove these unnecessary files.

**Comment by epfromer** [comment]
I just published v1.3.0 which incorporates all your feedback.
