### ISSUE TITLE
email body is empty

### ISSUE THREAD

**Issue by RezaRahmati** [epfromer/pst-extractor#25]
Hi I tried the library, I am able to retrieve the email subject and from, but for all emails email.body or email.bodyHTML or email.bodyPrefix is empty,

Also I am able to download some attachments but almost half of them has null value in .allData, while I am able to download the attachments and see body of emails using Kernel Outlook PST Viewer.

Wondering if there is a way to share the pst file privately with you, so you can help us to fix the issue?

**Comment by epfromer** [comment]
Hi Reza, sure, I can look into that although it may take me a week or two do get to it.  My email is epfromer at gmail.com.

**Comment by RezaRahmati** [comment]
@epfromer Thanks for fast response, I shared the pst file via google drive.

For checking issues none of emails in Inbox folder has body
For attachments all these attachemnts has null data
- uk-500.zip
- us-500.zip
- au-500.zip
- 1-MB-T~1.doc
- 10-MB-~1.doc
- 1-MB-T~1.xls

![image](https://user-images.githubusercontent.com/10086092/159133529-91ec3798-82ac-45fe-b56e-4fe82a3d6688.png)

**Comment by epfromer** [comment]
@RezaRahmati I've had some time to look into this problem, but I'm not sure I can reproduce your problem.  If you look in the example project, specifically the test.ts script, you can see in doSaveToFS() the logic to walk the attachments and extract each into a file.  I ran this script on your supplied PST and was able extract several attachments each which had content.  Specifically, for the 'Sample data' message highlighted above, both 2147844-1-MB-Test.xlsx and 2147844-10-MB-Test.docx have data.

**Comment by epfromer** [comment]
Version v1.9.0 has better handling of bodyHTML
