### ISSUE TITLE
Email extracted from .pst does not match the actual email

### ISSUE THREAD

**Issue by arshadali172** [epfromer/pst-extractor#3]
Hi,

pst-extractor is amazing! Thanks for the effort you put into this :)

I am having this issue where the email extracted from .pst does not match the actual email.

If you look at the email json extracted from .pst file using pst-extractor, you will notice that it is missing some lines that are in the actual email.

Is there some kind of max body length enforced by the library? 

<img width="578" alt="email object extracted from pst" src="https://user-images.githubusercontent.com/10674085/40288440-df03b6c6-5ce5-11e8-9555-116c88fb07da.png">
<img width="515" alt="actual email" src="https://user-images.githubusercontent.com/10674085/40288462-f318a57c-5ce5-11e8-8341-0a2772bbcd3c.PNG">

**Comment by epfromer** [comment]
Are you able to send me the PST for debugging?  If not, I can add debug logging and have you rerun the extraction.  That may help me isolate the problem.

**Comment by arshadali172** [comment]
Ahhh. sorry but how do I access the full 'body' property?

**Comment by epfromer** [comment]
Just grab it like you'd get the bodyPrefix.  Something like this in
TypeScript/JS:

let email: PSTMessage = folder.getNextChild();
console.log(email.body);

On Mon, May 21, 2018 at 6:29 AM, arshadali172 <notifications@github.com>
wrote:

> Ahhh. sorry but how do I access the full 'body' property?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepfromer%2Fpst-extractor%2Fissues%2F3%23issuecomment-390640270&data=02%7C01%7C%7C679932e47ac1422bebf908d5bf1690c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636625025989998375&sdata=l%2BVrP2Q%2F%2BwB6EOuIOB0QO3mM6zYam%2F53m5GoCBHw0DY%3D&reserved=0>,
> or mute the thread
> <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPdjQg1X72DEWNYA47-f1txC2l6xK_sRks5t0rNFgaJpZM4UGXZy&data=02%7C01%7C%7C679932e47ac1422bebf908d5bf1690c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636625025989998375&sdata=T7Sa3buYmZYARUjnGmW3Ir%2BFJBONmlJQNfn6kicZPlE%3D&reserved=0>
> .
>



-- 
Thanks,
Ed Pfromer

**Comment by arshadali172** [comment]
For some reason, ```body``` did not appear when I did ```console.log(JSON.stringify(email))```. Anyways, ```email.body``` works! Thanks

**Comment by epfromer** [comment]
Good.  Closing this issue.

**Comment by arshadali172** [comment]
Hi again Ed,

Thanks for helping out with my earlier query.

I have the extractor up and running now. I'm able to read the email body
and even the attachments. Sometimes, though I am simply unable to even read
the .pst file.

I get the following error. I think it's implying that the file is empty.
The size of the file is however 2MB.

Have you ever encountered this error? It's linked to the line - "const
pstFile = new PSTFile(resolve('archive.pst'))"

Thanks in advance,
Arshad

**Comment by epfromer** [comment]
What's the error?  I don't see it in your post.  I've extracted attachments > 2mb without issue.

**Comment by arshadali172** [comment]
Hi epfromer,

I attached the error as a screenshot. The 2 errors I get are either:
- throw new Error('PSTFile::open Invalid file header (expected: "!BDN"): '
+ buffer);
- throw new Error('PSTFile::findBtreeItem Unable to find node: ' + index +
' is desc: ' + descTree);

I have also attached the pst file that I tried to read using your library.
I have already done a sanity check on the file by opening it in outlook. Do
try that too to verify that the file is not corrupted.

Would appreciate it if you could share why I am unable to parse this file
using your library (or specifically the test.js code)

Appreciate any help you can provide :)

Best,
Arshad

**Comment by epfromer** [comment]
For some reason, I don't see any attachments.  Please send the error screenshot and PST file to  epfromer@gmail.com, and I'll look into it.  Thanks.
